### ISSUE TITLE
header missing on windows install?

### ISSUE THREAD

**Issue by tlambert03** [conda-forge/cimg-feedstock#7]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: `Cimg.h` doesn't seem to get added to the environment when installed on windows with `conda install -c conda-forge cimg`.  (works for linux).

The [recipe](https://github.com/conda-forge/cimg-feedstock/blob/master/recipe/build.bat) suggests it should make and add to the `include` folder ... but after install there is no folder (but the `cimg` record is added to `conda-meta`)

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
#
# Name                    Version                   Build  Channel
cimg                      2.9.7                h57928b3_0    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : test
            shell level : 3
       user config file : C:\Users\tjl10\.condarc
 populated config files : C:\Users\tjl10\.condarc
          conda version : 4.10.1
    conda-build version : 3.18.11
         python version : 3.7.3.final.0
       virtual packages : __cuda=11.1=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\tjl10\miniconda3  (writable)
      conda av data dir : C:\Users\tjl10\miniconda3\etc\conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\tjl10\miniconda3\pkgs
                          C:\Users\tjl10\.conda\pkgs
                          C:\Users\tjl10\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\tjl10\miniconda3\envs
                          C:\Users\tjl10\.conda\envs
                          C:\Users\tjl10\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.7.3 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

**Comment by din14970** [comment]
Sorry for the massive delay, I didn't get a ping. I basically copied the recipe that I found here: https://anaconda.org/dtk-forge/cimg/files. If it's not working I guess something is wrong with the bld.bat, most likely the syntax of the mkdir and xcopy commands. I'll see if I can find the correct syntax, however I can't test as I don't have access to any windows machine.

**Comment by din14970** [comment]
@tlambert03  I've now made a PR, maybe you can have a look if the bld.bat looks reasonable now?

**Comment by din14970** [comment]
It still doesn't work and I don't understand, it seems that nothing is packaged https://anaconda.org/conda-forge/cimg/files - the windows packages just contain the recipe. Will have to dig deeper.

**Comment by din14970** [comment]
Of course a temporary solution is simply downloading the linux or osx archive and manually copying the files to the right destination.

**Comment by din14970** [comment]
Ok I think the problem should now be resolved, the real issue was that my windows script was incorrectly named `build.bat` instead of `bld.bat`.

**Comment by tlambert03** [comment]
ahhh.  good one, sorry I didn't catch that!
